title: [Reiser Lab - Ephys setup documentation]
description: [Documentation on how to run ephys experiments on the G4 arena setup in the Reiser Lab at HHMI Janelia Research Campus]
theme: just-the-docs
search_enabled: true

url: https://leburnett.github.io/reiser-ephys-documentation

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
