title: [Reiser Lab Documentation]
description: [Documentation on how to run experiments on the G3/G4 LED arena setups in the Reiser Lab at HHMI Janelia Research Campus]
remote_theme: pmarsceill/just-the-docs 
search_enabled: true

url: "https://leburnett.github.io/reiser-documentation.com"
baseurl : "/reiser-documentation"

relative_links:
  enabled: true